#!/bin/bash

echo "SSO Frontend Integration Test"
echo "============================"
echo ""
echo "Frontend should be running on http://localhost:3000"
echo ""
echo "Test Steps:"
echo "1. Open http://localhost:3000 in your browser"
echo "2. Click 'Sign In' button"
echo "3. Select 'Login with Keycloak'"
echo "4. You should be redirected to Keycloak login page"
echo "5. Use admin/admin to login"
echo "6. You should be redirected back to the frontend"
echo "7. Check that you are logged in and can access the dashboard"
echo ""
echo "Debugging Tips:"
echo "- Check browser console for errors"
echo "- Check network tab for API calls"
echo "- Verify tokens are stored in localStorage:"
echo "  - auth_token (should contain accessToken)"
echo "  - auth_user (should contain user data)"
echo ""
echo "Common Issues:"
echo "- If stuck on /auth/success, check console for errors"
echo "- If 'Enable JavaScript' error, React app failed to load"
echo "- If unauthorized on API calls, token format may be wrong"