FROM alpine:latest

RUN apk add --no-cache postgresql-client zip curl bash coreutils tzdata \
    && cp /usr/share/zoneinfo/Europe/Berlin /etc/localtime && echo "Europe/Berlin" > /etc/timezone

COPY docker/backup/backup.sh /backup.sh
RUN chmod +x /backup.sh

COPY docker/backup/backup_run.sh /backup_run.sh
RUN chmod +x /backup_run.sh

CMD ["sh", "-c", "crond -f -L /dev/stdout"]