import { Student, Course, Assignment, Submission } from '../types';
import { User } from '../types/navigation';

export const mockStudents: Student[] = [
  {
    id: '1',
    givenName: 'John',
    familyName: 'Doe',
    email: 'john.doe@example.com',
    studentId: 'STU001',
    enrollmentDate: '2024-01-15',
    status: 'active',
    grade: 85,
  },
  {
    id: '2',
    givenName: 'Jane',
    familyName: 'Smith',
    email: 'jane.smith@example.com',
    studentId: 'STU002',
    enrollmentDate: '2024-01-16',
    status: 'active',
    grade: 92,
  },
  {
    id: '3',
    givenName: 'Bob',
    familyName: 'Johnson',
    email: 'bob.johnson@example.com',
    studentId: 'STU003',
    enrollmentDate: '2024-01-17',
    status: 'inactive',
    grade: 78,
  },
  {
    id: '4',
    givenName: 'Alice',
    familyName: 'Williams',
    email: 'alice.williams@example.com',
    studentId: 'STU004',
    enrollmentDate: '2024-01-18',
    status: 'active',
    grade: 96,
  },
  {
    id: '5',
    givenName: 'Charlie',
    familyName: 'Brown',
    email: 'charlie.brown@example.com',
    studentId: 'STU005',
    enrollmentDate: '2024-01-19',
    status: 'active',
    grade: 88,
  },
];

export const mockCourses: Course[] = [
  {
    id: '1',
    title: 'Introduction to Programming',
    description: 'Learn the fundamentals of programming with Python',
    code: 'CS101',
    semester: 'Fall 2024',
    credits: 3,
    instructor: 'Dr. Smith',
    enrolledStudents: 45,
    maxStudents: 50,
    status: 'active',
  },
  {
    id: '2',
    title: 'Data Structures and Algorithms',
    description: 'Advanced programming concepts and algorithmic thinking',
    code: 'CS201',
    semester: 'Fall 2024',
    credits: 4,
    instructor: 'Prof. Johnson',
    enrolledStudents: 38,
    maxStudents: 40,
    status: 'active',
  },
  {
    id: '3',
    title: 'Web Development',
    description: 'Full-stack web development with modern frameworks',
    code: 'CS301',
    semester: 'Fall 2024',
    credits: 3,
    instructor: 'Dr. Williams',
    enrolledStudents: 32,
    maxStudents: 35,
    status: 'active',
  },
];

export const mockAssignments: Assignment[] = [
  {
    id: '1',
    title: 'Basic Python Exercises',
    description: 'Complete the introductory Python programming exercises',
    courseId: '1',
    dueDate: '2024-02-15',
    maxScore: 100,
    submissionsCount: 42,
    status: 'published',
  },
  {
    id: '2',
    title: 'Binary Search Implementation',
    description: 'Implement binary search algorithm with complexity analysis',
    courseId: '2',
    dueDate: '2024-02-20',
    maxScore: 150,
    submissionsCount: 35,
    status: 'published',
  },
];

export const chartData = [
  { name: 'Jan', students: 120, courses: 8, submissions: 340 },
  { name: 'Feb', students: 135, courses: 9, submissions: 425 },
  { name: 'Mar', students: 142, courses: 10, submissions: 380 },
  { name: 'Apr', students: 158, courses: 11, submissions: 520 },
  { name: 'May', students: 165, courses: 12, submissions: 580 },
  { name: 'Jun', students: 178, courses: 12, submissions: 610 },
];

export const mockUser: User = {
  id: '1',
  name: 'Dr. John Smith',
  email: 'john.smith@university.edu',
  role: 'lecturer',
  permissions: [
    'view_students',
    'view_course_students',
    'create_assignments',
    'view_grades',
    'manage_course',
    'admin_access',
    'manage_users',
    'system_settings',
    'view_audit',
  ],
  courses: ['1', '2', '3'],
};